services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-rekt123}
      MYSQL_DATABASE: ${DB_NAME:-gametogether}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 2

  api:
    build: .
    ports:
      - "5000:8080"
      - "7191:7191"
    depends_on:
      mysql:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

    environment:
      ConnectionStrings__DefaultConnection: Server=${DB_SERVER:-mysql};Database=${DB_NAME:-gametogether};User=${DB_USER:-root};Password=${DB_PASSWORD:-rekt123};PORT=${DB_PORT:-3306};
      JwtSettings__SecretKey: ${SECRET_KEY:-C6821CD46246E81E9B481CD9D4D9A123} # Change this in production
      JwtSettings__Issuer: "GameTogether"
      JwtSettings__Audience: "GameTogetherApp"
      
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 2

  migrate:
    build:
      context: .
      target: build
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: Server=${DB_SERVER:-mysql};Database=${DB_NAME:-gametogether};User=${DB_USER:-root};Password=${DB_PASSWORD:-rekt123};PORT=${DB_PORT:-3306};
      JwtSettings__SecretKey: ${SECRET_KEY:-C6821CD46246E81E9B481CD9D4D9A123} # Change this in production
      JwtSettings__Issuer: "GameTogether"
      JwtSettings__Audience: "GameTogetherApp"
    working_dir: /src
    command: >
      sh -c "dotnet ef database update --project GameTogetherAPI/GameTogetherAPI.csproj --startup-project GameTogetherAPI/GameTogetherAPI.csproj"

  test:
    build:
      context: .
      target: build
    depends_on:
      mysql:
        condition: service_healthy 
      migrate:
        condition: service_completed_successfully
      api:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: Server=${DB_SERVER:-mysql};Database=${DB_NAME:-gametogether};User=${DB_USER:-root};Password=${DB_PASSWORD:-rekt123};PORT=${DB_PORT:-3306};
      JwtSettings__SecretKey: ${SECRET_KEY:-C6821CD46246E81E9B481CD9D4D9A123} # Change this in production
      JwtSettings__Issuer: "GameTogether"
      JwtSettings__Audience: "GameTogetherApp"
    command: dotnet test GameTogetherAPI.Test/GameTogetherAPI.Test.csproj --property:WarningLevel=0
