# Default environment file (.env) is loaded automatically
# For development: docker-compose up --build
# For production: Create a .env.prod file with real secrets (don't commit this file)
#Then run: docker-compose --env-file .env.prod up --build

x-common-env: &common-env
  ASPNETCORE_ENVIRONMENT: ${ENVIRONMENT}
  ConnectionStrings__DefaultConnection: ${CONNECTION_STRING}
  JwtSettings__SecretKey: ${JWT_SECRET}
  JwtSettings__Issuer: "GameTogether"
  JwtSettings__Audience: "GameTogetherApp"
  EmailSettings__VerificationUrl: ${EMAIL_VERIFICATION_URL}
  EmailSettings__SmtpServer: ${SMTP_SERVER}
  EmailSettings__Port: ${SMTP_PORT}
  EmailSettings__SenderEmail: ${SENDER_EMAIL}
  EmailSettings__SenderPassword: ${SENDER_PASSWORD}
  FrontendBaseUrl: ${FRONTEND_BASE_URL}

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-rekt123}
      MYSQL_DATABASE: ${DB_NAME:-gametogether}
    ports: ["3306:3306"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 2

  api:
    build:
      context: .
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    ports: ["5000:8080", "7191:7191"]
    depends_on:
      mysql:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment: *common-env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 2

  migrate:
    build:
      context: .
      args:
        - ENVIRONMENT=${ENVIRONMENT}
      target: build
    depends_on:
      mysql:
        condition: service_healthy
    environment: *common-env
    working_dir: /src
    command: >
      sh -c "dotnet ef database update --project GameTogetherAPI/GameTogetherAPI.csproj --startup-project GameTogetherAPI/GameTogetherAPI.csproj"

  test:
    build:
      context: .
      target: build
    depends_on:
      mysql:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      api:
        condition: service_healthy
    environment: *common-env
    command: dotnet test GameTogetherAPI.Test/GameTogetherAPI.Test.csproj --property:WarningLevel=0