name: Run Test Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

     # - name: Set up Docker Compose
      #  uses: docker/setup-compose-action@v1
       # with:
        #  version: 'latest'

      - name: Docker compose tests run
  # You may pin to the exact commit or the version.
  # uses: cloudposse/github-action-docker-compose-test-run@885bb157bac4a43ff80c24bc4df852635e348a03
        uses: cloudposse/github-action-docker-compose-test-run@0.2.0
        with:
          # Docker compose file
          file: Docker-Compose.yml
          # Service run tests inside
          service: test
          # Command to run tests
          command: docker compose up test
