name: Run Test Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/setup-compose@v2
        with:
          version: 'latest'

      - name: Build and run test service
        run: |
          docker-compose up -d
          docker-compose exec test-service-name run-tests
