name: Docker-CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and test
        uses: docker/build-push-action@v6
        with:
          target: build
          load: true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          target: final
          tags: ${{ secrets.DOCKER_USER }}/game-together-backend:latest
  
  
  deploy:
    environment: DTU Hosting
    runs-on: ubuntu-latest
    steps:
      - name: deploying
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker image pull ${{ secrets.DOCKER_USER }}/game-together-backend:latest
            docker container stop game-together-backend
            docker container rm game-together-backend
            docker container run -d --name game-together-backend -p 5238:5238 ${{ secrets.DOCKER_USER }}/game-together-backend
